name: personalapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  json_annotation: ^4.8.0
  provider: ^6.1.5
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_gen: ^5.10.0
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  shared_preferences: any
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/imagem/
    - assets/imagem/logo.png
    - assets/imagem/TelaLogin.png
    - assets/imagem/workout1.jpg
    - assets/imagem/meghan-holmes-wy_L8W0zcpI-unsplash.jpg
    - assets/imagem/victor-freitas-hOuJYX2K5DA-unsplash.jpg
    - assets/imagem/victor-freitas-WvDYdXDzkhs-unsplash.jpg
    - assets/imagem/danielle-cerullo-CQfNt66ttZM-unsplash.jpg
    - assets/imagem/scott-webb-U5kQvbQWoG0-unsplash.jpg
